package:
  name: pisad
  version: 1.1.0

source:
  url: https://github.com/ZhantianXu/PISAD/releases/download/v1.1.0/PISAD-1.1.0.tar.gz
  sha256: 2440e5fad5ed27fa951b13beb62e902ac71a4e70abc08df8d66cfd5beecf0950

build:
  skip: True # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage('pisad', max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
    - libtool
  host:
    - zlib
    - libgomp # [linux]
    - llvm-openmp # [osx]
  run:
    - libgomp # [linux]
    - llvm-openmp # [osx]
    - python
    - pyfaidx
    - numpy
    - scikit-learn
    - pandas
    - samtools
    - hdf5
    - boost
    - gperftools
    - dsk
    - matplotlib-base
    - perl
    - make

test:
  commands:
    - pisadCount -h
    - pisadEval -h
    - run.sh -h

about:
  home: "https://github.com/ZhantianXu/PISAD"
  summary: "pisad - Phsaed Intraspecies Sample Anomalies Detection tool"
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
